@echo off
color c
echo THIS METHOD WILL INSTALL A DIFFERENT STEAM AT A DIFFERENT LOCATION INSTEAD OF OVERWRITING YOUR MAIN STEAM.
echo THIS METHOD ALSO SKIPS ALL THE MANUALLY SETUP AND GIVES YOU A STEAM THAT HAS ALREADY BEEN CONFIGURED.
echo CONTINUE?
pause
start
